create sequence patient_id_seq start 1;
create sequence doctor_id_seq start 1;
create sequence staff_id_seq start 1;
create sequence appointment_id_seq start 1;
create sequence medicalhistory_id_seq start 1;
create sequence prescription_id_seq start 1;
create sequence room_id_seq start 1;
create sequence equipment_id_seq start 1;
create sequence bill_id_seq start 1;